### ISSUE TITLE
大佬，能发我一下权重文件吗，实在找不到，万分谢谢 

### ISSUE THREAD

**Issue by idcien** [yzfzzz/Stereo-Detection#1]
大佬，能发我一下权重文件吗，实在找不到，万分谢谢 
13938052804@163.com

**Comment by yzfzzz** [comment]
使用这个项目之前建议看一下[这个视频](https://www.bilibili.com/video/BV1FZ4y1m777/)，里面会告诉你权重在哪里。对于需要使用Tensorrt加速的，我使用的是[官方的权重](https://github.com/ultralytics/yolov5)
