### ISSUE TITLE
关于SGBM算法的问题

### ISSUE THREAD

**Issue by Asurasin** [yzfzzz/Stereo-Detection#10]
文件中用的SGBM算法可以使用GPU进行加速吗？如果加速的话，能否指导一下如何修改，如果使用自己的 stereo matching 算法，是不是将视差计算的过程换成自己的就可以了？

**Comment by hahaqiu123** [comment]
同求GPU加速

**Comment by yzfzzz** [comment]
GPU加速要用C++重构SGBM，然后用C++部署yolov5.比较麻烦所以我没弄
也欢迎大佬提交GPU加速的代码！
