### ISSUE TITLE
双目相机型号

### ISSUE THREAD

**Issue by bossxie1111** [yzfzzz/Stereo-Detection#2]
您好想问下您的双目相机是400万像素还是130万像素的呀？

**Comment by yzfzzz** [comment]
应该是400万像素的：[常见问题答疑](https://github.com/yzfzzz/Stereo-Detection/blob/main/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E7%AD%94%E7%96%91.md)
