### ISSUE TITLE
SGBM算法是否可用GPU加速

### ISSUE THREAD

**Issue by Sniper0913** [yzfzzz/Stereo-Detection#20]
博主你好，在B站上学习了大佬的在YOLOv5中加入双目测距，想请教一下SGBM算法部分是否可以使用GPU加速？如果可用，代码应该修改哪些部分。

**Comment by yzfzzz** [comment]
python版本的opencv不能使用gpu加速(没有这个功能)，C++版本的可以

**Comment by Sniper0913** [comment]
> python版本的opencv不能使用gpu加速(没有这个功能)，C++版本的可以

好的，谢谢大佬
