### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by wangdandang** [yzfzzz/Stereo-Detection#3]
大佬，做人员定位，深度在0~20m，该选用焦距为多少的镜头，基线可调。你用的摄像头最远可以测多远？参数可以说一下么

**Comment by wangdandang** [comment]
基线最高在20cm左右

**Comment by yzfzzz** [comment]
大概25米左右吧，参数的话在这里：[相机参数](https://github.com/yzfzzz/Stereo-Detection/blob/main/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E7%AD%94%E7%96%91.md)
