### ISSUE TITLE
调用不了双目摄像头问题

### ISSUE THREAD

**Issue by shaowlgz** [yzfzzz/Stereo-Detection#6]
在predict.py中按照注释将video path 改为 0，但是运行时报错，显示内容如下
File "/home/lgz/桌面/yolov5-v6.1-pytorch-master/predict.py", line 103, in <module>
    raise ValueError("未能正确读取摄像头（视频），请注意是否正确安装摄像头（是否正确填写视频路径）。")
ValueError: 未能正确读取摄像头（视频），请注意是否正确安装摄像头（是否正确填写视频路径）。

**Comment by shaowlgz** [comment]
请问这个问题如何解决呢

**Comment by uxfion** [comment]
看下我这个[issue#5](https://github.com/yzfzzz/Stereo-Detection/issues/5)吧，我是可以调用的
