### ISSUE TITLE
调用摄像头问题

### ISSUE THREAD

**Issue by shaowlgz** [yzfzzz/Stereo-Detection#7]
示例教程可以正常使用（car.avi）但是改为调用双目摄像头，就报错，报错情况如下：
Traceback (most recent call last):
  File "/home/lgz/桌面/yolov5-v6.1-pytorch-master/predict.py", line 117, in <module>
    frame = np.array(yolo.detect_image(frame))
  File "/home/lgz/桌面/yolov5-v6.1-pytorch-master/yolo.py", line 165, in detect_image
    imgR = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
请问如何解决这个问题啊

**Comment by uxfion** [comment]
看下我这个[issue#5](https://github.com/yzfzzz/Stereo-Detection/issues/5)吧，我是可以调用的

**Comment by shaowlgz** [comment]
> 看下我这个[issue#5](https://github.com/yzfzzz/Stereo-Detection/issues/5)吧，我是可以调用的

不行的，我的和你的问题不一样，我的双目相机默认图片尺寸是2560*720，都是按照这个来修改的，方便加一下联系方式吗，您留个联系方式，我加你（有偿）

**Comment by uxfion** [comment]
不用啊，你直接在这交流就好了，先去看一下双目相机的参数，我的是这个![image](https://user-images.githubusercontent.com/44778029/231674682-d80d2e41-883c-42d0-980a-49e7784bc8f5.png)，所以你就需要将摄像头的

```
cap = cv2.VideoCapture(0)
cap.set(3, 480) # 设置摄像头分辨率，3为高，4为宽
cap.set(4, 1280)
```

如果的摄像头不支持这个参数，程序就会报错，你需要把分辨率改成支持的，然后代码里的把图片分割也要改下

**Comment by shaowlgz** [comment]
> 不用啊，你直接在这交流就好了，先去看一下双目相机的参数，我的是这个： ![d6c36c81cc3e6cc9dc8ef364b76286e](https://user-images.githubusercontent.com/44778029/231689593-56213860-3a19-408e-8cde-5b45fb75e4e7.jpg)
> 
> 所以你就需要将摄像头的分辨率设置为如下：
> 
> ```
> capture = cv2.VideoCapture(0)
> capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
> capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
> ```
> 
> 如果的摄像头不支持这个参数，程序就会报错，你需要把分辨率改成支持的，然后代码里图片分割的部分也要改下
> 
> https://github.com/yzfzzz/Stereo-Detection/blob/7d942a8333905d31e6ff55726a3b9456a432d32c/Jeston%20nano_tensorrt/%E9%83%A8%E7%BD%B2/python_trt.py#L135

问题解决了，太感谢了，少加了这两行代码
capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
